
import { UserRole, Region, Branch, PromoType, User, RequestStatus, MarketingRequest } from './types';

export const REGIONS: Region[] = [
  { id: 'reg1', name: 'Андижон 1' },
  { id: 'reg2', name: 'Андижон 2' },
  { id: 'reg3', name: 'Бухоро' },
  { id: 'reg4', name: 'Жиззах-Сирдарё' },
  { id: 'reg5', name: 'Кашкадарё' },
  { id: 'reg6', name: 'Навоий' },
  { id: 'reg7', name: 'Наманган' },
  { id: 'reg8', name: 'Самарканд' },
  { id: 'reg9', name: 'Сурхондарё' },
  { id: 'reg10', name: 'Тошкент 1' },
  { id: 'reg11', name: 'Тошкент 2' },
  { id: 'reg12', name: 'Фаргона' },
  { id: 'reg13', name: 'Хоразм' },
];

export const BRANCHES: Branch[] = [
{ id: '53', name: 'Андижон мини', regionId: 'reg1' },
{ id: '76', name: 'Андижон-2', regionId: 'reg1' },
{ id: '28', name: 'Андижон', regionId: 'reg1' },
{ id: '132', name: 'Андижон-Клиника', regionId: 'reg1' },
{ id: '23', name: 'Баликчи', regionId: 'reg1' },
{ id: '25', name: 'Избоскан', regionId: 'reg1' },
{ id: '31', name: 'Олтинкул', regionId: 'reg1' },
{ id: '11', name: 'Хужаобод', regionId: 'reg1' },
{ id: '123', name: 'Шахрихон', regionId: 'reg1' },
{ id: '14', name: 'Асака', regionId: 'reg2' },
{ id: '21', name: 'Булокбоши', regionId: 'reg2' },
{ id: '32', name: 'Жалакудук', regionId: 'reg2' },
{ id: '18', name: 'Кургонтепа', regionId: 'reg2' },
{ id: '29', name: 'Мархамат', regionId: 'reg2' },
{ id: '30', name: 'Пахтаобод', regionId: 'reg2' },
{ id: '54', name: 'Хонобод мини', regionId: 'reg2' },
{ id: '40', name: 'Бухоро', regionId: 'reg3' },
{ id: '59', name: 'Вобкент', regionId: 'reg3' },
{ id: '108', name: 'Галаосиё', regionId: 'reg3' },
{ id: '81', name: 'Жондор', regionId: 'reg3' },
{ id: '107', name: 'Когон', regionId: 'reg3' },
{ id: '63', name: 'Коракул', regionId: 'reg3' },
{ id: '112', name: 'Олот', regionId: 'reg3' },
{ id: '98', name: 'Пешку', regionId: 'reg3' },
{ id: '64', name: 'Ромитон', regionId: 'reg3' },
{ id: '142', name: 'Бахмал', regionId: 'reg4' },
{ id: '119', name: 'Боёвут', regionId: 'reg4' },
{ id: '67', name: 'Галлаорол', regionId: 'reg4' },
{ id: '36', name: 'Гулистон', regionId: 'reg4' },
{ id: '57', name: 'Жиззах', regionId: 'reg4' },
{ id: '115', name: 'Зомин', regionId: 'reg4' },
{ id: '89', name: 'Пахтакор', regionId: 'reg4' },
{ id: '62', name: 'Сирдарё', regionId: 'reg4' },
{ id: '79', name: 'Янгиер', regionId: 'reg4' },
{ id: '109', name: 'Бешкент', regionId: 'reg5' },
{ id: '50', name: 'Гузор', regionId: 'reg5' },
{ id: '38', name: 'Карши', regionId: 'reg5' },
{ id: '191', name: 'Карши мобил', regionId: 'reg5' },
{ id: '78', name: 'Касби', regionId: 'reg5' },
{ id: '49', name: 'Косон', regionId: 'reg5' },
{ id: '60', name: 'Чирокчи', regionId: 'reg5' },
{ id: '39', name: 'Шахрисабз', regionId: 'reg5' },
{ id: '192', name: 'Шахрисабз мобил', regionId: 'reg5' },
{ id: '102', name: 'Яккабог', regionId: 'reg5' },
{ id: '194', name: 'Кукдала', regionId: 'reg5' },
{ id: '99', name: 'Гиждувон', regionId: 'reg6' },
{ id: '47', name: 'Зарафшон', regionId: 'reg6' },
{ id: '94', name: 'Кизилтепа', regionId: 'reg6' },
{ id: '110', name: 'Навбахор', regionId: 'reg6' },
{ id: '48', name: 'Навоий', regionId: 'reg6' },
{ id: '106', name: 'Нурота', regionId: 'reg6' },
{ id: '58', name: 'Учкудук', regionId: 'reg6' },
{ id: '85', name: 'Шофиркон', regionId: 'reg6' },
{ id: '165', name: 'Хатирчи', regionId: 'reg6' },
{ id: '134', name: 'Косонсой', regionId: 'reg7' },
{ id: '20', name: 'Мингбулок', regionId: 'reg7' },
{ id: '9', name: 'Наманган', regionId: 'reg7' },
{ id: '75', name: 'Наманган 2', regionId: 'reg7' },
{ id: '97', name: 'Поп', regionId: 'reg7' },
{ id: '104', name: 'Тошбулок', regionId: 'reg7' },
{ id: '27', name: 'Уйчи', regionId: 'reg7' },
{ id: '17', name: 'Учкургон', regionId: 'reg7' },
{ id: '16', name: 'Чорток', regionId: 'reg7' },
{ id: '10', name: 'Чуст', regionId: 'reg7' },
{ id: '15', name: 'Янгикургон', regionId: 'reg7' },
{ id: '90', name: 'Булунгур', regionId: 'reg8' },
{ id: '77', name: 'Жомбой', regionId: 'reg8' },
{ id: '43', name: 'Иштихон', regionId: 'reg8' },
{ id: '52', name: 'Каттакургон', regionId: 'reg8' },
{ id: '86', name: 'Кушрабод', regionId: 'reg8' },
{ id: '88', name: 'Нарпай', regionId: 'reg8' },
{ id: '84', name: 'Нуробод', regionId: 'reg8' },
{ id: '143', name: 'Окдарё', regionId: 'reg8' },
{ id: '176', name: 'Пайарик', regionId: 'reg8' },
{ id: '175', name: 'Пастдаргом', regionId: 'reg8' },
{ id: '182', name: 'Пахтачи', regionId: 'reg8' },
{ id: '41', name: 'Самарканд', regionId: 'reg8' },
{ id: '42', name: 'Ургут', regionId: 'reg8' },
{ id: '178', name: 'Самарканд 2', regionId: 'reg8' },
{ id: '144', name: 'Каттакургон 2', regionId: 'reg8' },
{ id: '103', name: 'Олтинсой', regionId: 'reg9' },
{ id: '135', name: 'Ангор', regionId: 'reg9' },
{ id: '82', name: 'Денов', regionId: 'reg9' },
{ id: '101', name: 'Жаркургон', regionId: 'reg9' },
{ id: '169', name: 'Кизирик', regionId: 'reg9' },
{ id: '186', name: 'Кумкургон', regionId: 'reg9' },
{ id: '180', name: 'Термиз', regionId: 'reg9' },
{ id: '137', name: 'Узун', regionId: 'reg9' },
{ id: '105', name: 'Шеробод', regionId: 'reg9' },
{ id: '121', name: 'Шурчи', regionId: 'reg9' },
{ id: '72', name: 'Газалкент', regionId: 'reg10' },
{ id: '100', name: 'Зангиота', regionId: 'reg10' },
{ id: '87', name: 'Келес', regionId: 'reg10' },
{ id: '65', name: 'Кибрай', regionId: 'reg10' },
{ id: '83', name: 'Куйи Чирчик', regionId: 'reg10' },
{ id: '61', name: 'Оккургон', regionId: 'reg10' },
{ id: '117', name: 'Паркент', regionId: 'reg10' },
{ id: '24', name: 'Чирчик', regionId: 'reg10' },
{ id: '55', name: 'Чирчик мини', regionId: 'reg10' },
{ id: '71', name: 'Юкори Чирчик', regionId: 'reg10' },
{ id: '19', name: 'Янгийул', regionId: 'reg10' },
{ id: '66', name: 'Ангрен', regionId: 'reg11' },
{ id: '113', name: 'Бекобод', regionId: 'reg11' },
{ id: '96', name: 'Бука', regionId: 'reg11' },
{ id: '114', name: 'Зафар', regionId: 'reg11' },
{ id: '26', name: 'Олмалик', regionId: 'reg11' },
{ id: '73', name: 'Пскент', regionId: 'reg11' },
{ id: '13', name: 'Богдод', regionId: 'reg12' },
{ id: '5', name: 'Бешарик', regionId: 'reg12' },
{ id: '133', name: 'Дангара', regionId: 'reg12' },
{ id: '7', name: 'Кува', regionId: 'reg12' },
{ id: '2', name: 'Кукон', regionId: 'reg12' },
{ id: '8', name: 'Тошлок', regionId: 'reg12' },
{ id: '4', name: 'Учкуприк', regionId: 'reg12' },
{ id: '3', name: 'Фаргона', regionId: 'reg12' },
{ id: '141', name: 'Фаргона ЦУМ', regionId: 'reg12' },
{ id: '12', name: 'Яйпан', regionId: 'reg12' },
{ id: '95', name: 'Амударё', regionId: 'reg13' },
{ id: '46', name: 'Беруний', regionId: 'reg13' },
{ id: '68', name: 'Богот', regionId: 'reg13' },
{ id: '45', name: 'Гурлан', regionId: 'reg13' },
{ id: '93', name: 'Кунгирот', regionId: 'reg13' },
{ id: '91', name: 'Нукус', regionId: 'reg13' },
{ id: '92', name: 'Турткул', regionId: 'reg13' },
{ id: '37', name: 'Урганч', regionId: 'reg13' },
{ id: '51', name: 'Хазорасп', regionId: 'reg13' },
{ id: '44', name: 'Хива', regionId: 'reg13' },
{ id: '69', name: 'Хонка', regionId: 'reg13' },
{ id: '118', name: 'Хужайли', regionId: 'reg13' },
{ id: '122', name: 'Чимбой', regionId: 'reg13' },
{ id: '70', name: 'Шовот', regionId: 'reg13' },
{ id: '147', name: 'Элликкала', regionId: 'reg13' },
{ id: '159', name: 'Тахиятош', regionId: 'reg13' },
];

export const PROMO_TYPES: PromoType[] = [
  { id: 'p1', name: 'Смарт акция' },
  { id: 'p2', name: 'Промоутер' },
  { id: 'p3', name: 'Таргет' },
  { id: 'p4', name: 'Телеграм/инстаграм реклама' },
  { id: 'p5', name: 'СМС Апп' },
  { id: 'p6', name: 'Бошка' },
];

export const INITIAL_USERS: User[] = [
  // 7 RTMs
  { id: 'rtm1', name: 'Хакимов Исфандиёр', role: UserRole.RTM, regionId: ['reg1','reg2'], password: '123' },
  { id: 'rtm2', name: 'Тешабоев Аброр', role: UserRole.RTM, regionId: ['reg10','reg11'], password: '123' },
  { id: 'rtm3', name: 'Комилов Бекзод', role: UserRole.RTM, regionId: ['reg5','reg9'], password: '123' },
  { id: 'rtm4', name: 'Хакимов Шерзод', role: UserRole.RTM, regionId: ['reg3','reg6'], password: '123' },
  { id: 'rtm5', name: 'Равшанов Жахонгир', role: UserRole.RTM, regionId: ['reg4','reg8'], password: '123' },
  { id: 'rtm6', name: 'Водий', role: UserRole.RTM, regionId: ['reg7','reg12'], password: '123' },
  { id: 'rtm7', name: 'Хоразм', role: UserRole.RTM, regionId: 'reg13', password: '123' },
  
  // Management & Back-office
  { id: 'tm1', name: 'Зохиджон', role: UserRole.TM, password: '123' },
  { id: 'as1', name: 'Сабина', role: UserRole.ASSISTANT, password: '123' },
  { id: 'fi1', name: 'Шерзодбек', role: UserRole.FINANCE, password: '123' },
  { id: 'ad1', name: 'Администратор', role: UserRole.ADMIN, password: 'admin' },
];

export const STATUS_MAP: Record<RequestStatus, { label: string; color: string }> = {
  [RequestStatus.PENDING_TM]: { label: 'На рассмотрении ТМ', color: 'bg-amber-100 text-amber-700 border-amber-200' },
  [RequestStatus.APPROVED_TM]: { label: 'Одобрено ТМ', color: 'bg-green-100 text-green-700 border-green-200' },
  [RequestStatus.PARTIAL_TM]: { label: 'Частично одобрено', color: 'bg-blue-100 text-blue-700 border-blue-200' },
  [RequestStatus.REJECTED]: { label: 'Отклонено', color: 'bg-red-100 text-red-700 border-red-200' },
  [RequestStatus.SIGNED]: { label: 'Подписано / В финотделе', color: 'bg-purple-100 text-purple-700 border-purple-200' },
  [RequestStatus.PAID]: { label: 'Оплачено', color: 'bg-slate-900 text-white border-slate-900' },
};

export const INITIAL_REQUESTS: MarketingRequest[] = [];
